name: smssos
description: "Secure my Space. Sending emergency messages application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  ed25519_key_pair:
    git:
      url: https://github.com/eses-git/ed25519_key_pair
  uuid: ^4.5.1
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.0
  picovoice_flutter: ^3.0.0
  flutter_contacts: ^1.1.9+2
  path_provider: ^2.0.12
  flutter_sound: ^9.6.0
  intl: ^0.19.0
  flutter_archive: ^6.0.3
  http: ^1.2.2
  offline_listening:
    path: ../offline_listening

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add the `commands` directory to the assets section
  assets:
    - assets/commands/
